name: NERC Netbox CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  env_var: ${{ vars.NETBOX_URL }}

jobs:
  # This workflow contains a single job called "build"
  build:
    environment: ${{ github.ref_name != 'main' && 'NETBOX_API_DEV' || 'NETBOX_API' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/minitriga/netbox-device-type-library-import
      env:
        NETBOX_URL: ${{ vars.NETBOX_URL }}
        NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}
        REPO_URL: ${{ vars.REPO_URL }}
        REPO_BRANCH: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Report Netbox URL
        run: echo $NETBOX_URL

      - name: Run import script
        run: python3 -u nb-dt-import.py

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
