name: NERC Netbox CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  post_to_netbox:
    environment: ${{ github.ref != 'refs/heads/main' && 'NETBOX_API_DEV' || 'NETBOX_API' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/minitriga/netbox-device-type-library-import
      env:
        NETBOX_URL: ${{ vars.NETBOX_URL }}
        NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}
        REPO_URL: ${{ vars.REPO_URL }}
        REPO_BRANCH: ${{ github.head_ref == '' && 'main' || github.head_ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Report Netbox URL
        run: echo $NETBOX_URL

      - name: Report repo branch
        run: |
          echo $REPO_BRANCH
          echo $GITHUB_HEAD_REF

      - name: Run import script
        run: python3 -u /app/nb-dt-import.py
